# Generated by Django 4.1 on 2022-09-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('director', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('genero', models.CharField(max_length=30)),
                ('temporadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('director', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('director', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('genero', models.CharField(max_length=30)),
                ('temporadas', models.IntegerField()),
            ],
        ),
    ]
