# Generated by Django 4.1 on 2022-10-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMovies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='año',
            new_name='anio',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
