# Generated by Django 4.1 on 2022-10-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMovies', '0002_rename_año_pelicula_anio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='anio',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
